blog/urls.py
from django.urls import path
from .views import (
    PostListView, 
    PostDetailView, 
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    like_post,
)

app_name = 'blog'

urlpatterns = [
    path('',PostListView, name='post-list'),
    path('tag/<slug:tag_slug>/',PostListView, name='post-list-by-tag'),
    path('search/',PostListView, name='post-by-search'),
    path('<int:pk>/',PostDetailView,name='post-detail'),
    path('user/<str:username>', UserPostListView, name='user-posts'), 
    path('<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),    
    path('new/', PostCreateView.as_view(),name='post-create'),
    path('like/', like_post, name='like'),
]

coverprey/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views
from users.forms import CustomAuthForm


urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(authentication_form=CustomAuthForm, 
            template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('oauth/',include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__', include(debug_toolbar.urls))]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

class Post(models.Model):

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField(verbose_name='Content')
    book_name = models.CharField(max_length=250)
    author_name = models.CharField(max_length=100)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    likes = models.ManyToManyField(User, related_name='likes', blank=True)
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title
    
    def total_likes(self):
        return self.likes.count()

    def get_absolute_url(self):
        return reverse('blog:post-detail',kwargs={'pk': self.pk})


class Comment(models.Model):
    body = models.TextField()
    post = models.ForeignKey(Post,on_delete=models.CASCADE,
                             related_name='post_comments')
    author = models.ForeignKey(User,on_delete=models.CASCADE,
                               related_name='user_comments')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return self.body

blog/forms.py
from .models import Post, Comment
from django import forms


class CommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(CommentForm, self).__init__(*args, **kwargs)
        self.fields['body'].widget.attrs = {
            'placeholder': 'Write a comment here...',
            'id' : 'comment-create'
        }

    class Meta:
        model = Comment
        fields = ('body',)

class MyCreateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(MyCreateForm, self).__init__(*args, **kwargs)
        self.fields['title'].widget.attrs = {
            'placeholder': 'title',
            'id' : 'title-create'
        }
        self.fields['body'].widget.attrs = {
            'placeholder': 'write something',
            'id' : 'body-create'
        }
        self.fields['book_name'].widget.attrs = {
            'placeholder': 'book name',
            'id' : 'book-create'
        }     
        self.fields['author_name'].widget.attrs = {
            'placeholder': 'author name',
            'id' : 'author-create'
        }     
        self.fields['tags'].widget.attrs = {
            'placeholder': 'tags (A comma seperated list of tags)',
            'id' : 'tags-create'
        }     

    class Meta:
        model = Post
        fields = ['title', 'body', 'book_name', 'author_name', 'tags']

blog/views.py
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_POST
from django.template.loader import render_to_string
from django.db.models.functions import Greatest
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.db.models import Count
from taggit.models import Tag
from .models import Post, Comment
from .forms import CommentForm, MyCreateForm
from django.views.generic import (ListView,  
                                  CreateView,
                                  UpdateView,
                                  DeleteView,
                            )   


# class PostListView(LoginRequiredMixin, ListView):
#     login_url = '/login/'
#     model = Post
#     context_object_name = 'posts'
#     paginate_by = 4
#     template_name = 'blog/post_list.html'
#     ordering = ['-publish']


@login_required(login_url='/login/')
def PostListView(request, tag_slug=None):
    posts = Post.objects.order_by('-publish')
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])
    
    # To get most common tags
    commonTags = Post.tags.most_common()[:20]

    # For searched posts
    if request.GET.get('q') is not None:
        query = request.GET.get('q')
        # search_vector = SearchVector('book_name', weight='A') + \
        #                 SearchVector('author_name',weight='A') + \
        #                 SearchVector('title',weight='A') + \
        #                 SearchVector('body',weight='B')
        # search_query = SearchQuery(query)

        # posts = Post.objects.annotate(rank=SearchRank(search_vector, search_query))\
        #                             .filter(rank__gte=0.3).order_by('-rank')
        posts = Post.objects.annotate(
            similarity=Greatest(
                TrigramSimilarity('book_name', query),
                TrigramSimilarity('author_name', query),
                TrigramSimilarity('title', query)
            )).filter(similarity__gte=0.1).order_by('-similarity')

    # For Pagination
    paginator = Paginator(posts, 8) # 8 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post_list.html', {'page': page,
                                                   'posts': posts,
                                                   'tag':tag,
                                                   'commontags':commonTags})

@login_required(login_url='/login/')
def PostDetailView(request, pk):
    user = request.user
    post = get_object_or_404(Post, pk=pk)
    comments = post.post_comments.all()

    new_comment = None

    if request.method == 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.author = user
            new_comment.save()
            return redirect('blog:post-detail', pk)
    else:
        comment_form = CommentForm()

    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.objects.filter(tags__in=post_tags_ids)\
                                  .exclude(pk=pk)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('-same_tags','-publish')[:5]


    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        is_liked = True

    if request.is_ajax():
        html = render_to_string('blog/like_section.html', context, request=request)
        return JsonResponse({'form': html})

    return render(request, 'blog/post_detail.html', 
                            {'post': post,
                            'comments': comments,
                            'new_comment': new_comment,
                            'comment_form': comment_form,
                            'similar_posts': similar_posts,
                            'total_likes': post.total_likes(),
                            'is_liked': is_liked,
                        })


class PostCreateView(LoginRequiredMixin, CreateView):
    # model = Post
    # fields = ['title', 'body', 'book_name', 'author_name', 'tags']
    form_class = MyCreateForm
    template_name = 'blog/post_create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'body']
    template_name = 'blog/post_form.html'
    success_url = reverse_lazy('blog:post-list')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False

class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blog:post-list')

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def UserPostListView(request, username):
    user = get_object_or_404(User, username=username)
    posts = Post.objects.filter(author=user)


    paginator = Paginator(posts, 4) # 4 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)


    return render(request, 'blog/user_posts.html', {'posts':posts, 
                                                    'thisuser':user,
                                                    'page':page})


@login_required
def like_post(request):
    post = get_object_or_404(Post, id=request.POST.get('id'))
    is_liked = False
    if post.likes.filter(id=request.user.id).exists():
        post.likes.remove(request.user)
        is_liked = False
    else:
        post.likes.add(request.user)
        is_liked = True
    context = {
        'post': post,
        'is_liked': is_liked,
        'total_likes': post.total_likes(),
    }
    if request.is_ajax():
        html = render_to_string('blog/like_section.html', context, request=request)
        return JsonResponse({'form': html})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/main.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Quicksand&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Barlow&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">

    <!-- FONT AWESOME -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>{% block title %}{% endblock %}</title>
</head>
<body class="background-body" >
<div class="background-body">
    <nav id="navopa">
    <ul>            
        <div class="container">
            <div>
                <li id="coverprey"><a href="{% url 'blog:post-list' %}"><i class="fa fa-newspaper-o" style="font-size:23px; color: #279ad8;"></i><span style="color: white;">COVERPREY</span></a></li>
            </div> 
            <div class="topnav-right">
                    <li><a href="{% url 'profile' %}"><i class="fa fa-user" style="font-size:23px; color: #ffffff;"></i></a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'logout' %}"><i class="fa fa-sign-out" style="font-size:23px; color: #ffffff;"></i></a></li>  
                {% else %}
                    <li><a href="{% url 'login' %}">Login</a></li>
                {% endif %}  
                        
            </div>  
        </div>      
    </ul>
    </nav>
    <div class="container">
        <div class="extra-content"></div>
        {% if messages %}
            {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
    {% block content %}

    {% endblock %}

    </div>
    <div class="footer-note">
        <div class="footer-bar"></div>
        <div class="container">
            <div style="font-family: 'Muli', sans-serif;" class="footer-items" >
                <div class="footer-contents">
                    <a class="footer-cover" href="{% url 'blog:post-list' %}">
                        <i class="fa fa-newspaper-o" style="font-size:23px; color: #279ad8;"></i>
                        <span id="coverprey" style="color: white;"> COVERPREY</span>
                    </a> <br>
                    About <br>
                    Explore <br>
                    Privacy <br>
                    T & C <br>
                </div>
                <div class="footer-contents">
                    <br> Help <br>
                    Services <br>
                    Promotions <br>
                </div>
                <div class="footer-contents">
                    <br> <div style="font-size: 20px;" ><u>Contacts</u></div>

                    <strong>mail:</strong>: theshashank6872@gmail.com <br>
                    <strong>Mob:</strong> +91-7488607770 <br>
                    <strong>Website:</strong> 
                        <a style="color: #6ec4ec;" class="footer-cover" href="shash68i.github.com/me">
                            shash68i.github.com/me
                        </a>
                    <br>
                    <strong>LinkedIn:</strong> 
                        <a style="color: #6ec4ec;" class="footer-cover" href="https://www.linkedin.com/in/shashank-kashyap-a65930156">
                            https://www.linkedin.com/in/shashank-kashyap-a65930156 
                        </a>
                </div>
            </div>
            <div class="copyright-section">
                <i class="fa fa-copyright" style="font-size:18px; color: white;"></i><span style="color: white;"> 2020 coverprey</span>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <script type="text/javascript">
        $(document).on('click', '#like', function(event){
            event.preventDefault();
            var pk = $(this).attr('value');
            $.ajax({
            type: 'POST',
            url: '{% url "blog:like" %}',
            data: {'id':pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'},
            dataType: 'json',
            success: function(response){
                $('#like-section').html(response['form'])
                console.log($('#like-section').html(response['form']));
            },
            error: function(rs, e){
                console.log(rs.responseText);
            },
            });
        });
    </script>
</body>
</html>

blog/templates/blog/like_section.html
<div style="display:flex;">
  <div>
    {% if request.user.is_authenticated %}
      <form action="{% url 'blog:like' %}" method="post">
        {% csrf_token %}

        {% if is_liked %}
          <button class="detail-like" type="submit" id="like" name="post_id" value="{{ post.id }}">
            <i class="fa fa-heart" style="font-size:28px; color:red"></i>
          </button>
        {% else %}
          <button class="detail-like" type="submit" id="like" name="post_id" value="{{ post.id }}">
            <i class="fa fa-heart-o" style="font-size:28px; color:red"></i>
          </button>
        {% endif %}
      </form>
    {% endif %}
  </div>

  <div style="font-size: 22px;" class="ml-2">{{ total_likes }} Like{{ total_likes|pluralize }}</div>
</div>

blog/templates/blog/pagination.html
<div class="pagination">
    <span class="step-links">
    {% if page.has_previous %}
        <a href="?page={{ page.previous_page_number }}"> <button class="page-btn">Previous</button></a>
    {% endif %}
        <span class="current">
            Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
    {% if page.has_next %}
        <a href="?page={{ page.next_page_number }}"><button class="page-btn">Next</button></a>
    {% endif %}
    </span>
</div>

blog/templates/blog/post_confirm_delete.html
{% extends "blog/base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'blog:post-detail' object.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_create.html
{% extends 'blog/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<div class="post-create-form">

    <h3 id="create-heading" >Add a post</h3>  
    <form method="POST">
        {% csrf_token %}
        <div class="post-create-form-fields">
            <p>{{form.title}}</p>
            <p>{{form.body}}</p>
            <p>{{form.book_name}}</p>
            <p>{{form.author_name}}</p>
            <p>{{form.tags}}</p>
        </div>
            <button class="post-create-button float-right" type="submit">POST</button>
    </form>
</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="row">
  <div class="col-8">
      <div class="my-font post-detail">
          <div><h3 style="font-weight: 700;" class="my-font">{{post.title}}</h3></div>
          <div class="update-delete-buttons">
              {% if post.author == user %}
                <a class="my-font2 btn btn-secondary btn-sm mt-1 ml-2 mb-1" href="{% url 'blog:post-update' post.id %}">Update</a>
                <a class="my-font2 btn btn-danger btn-sm ml-1 mt-1 mb-1" href="{% url 'blog:post-delete' post.id %}">Delete</a>
              {% endif %}
          </div>      
      </div>
         <span class="my-font2" style="font-size:18px;">{{post.body}}</span> 
      <br>
      <hr>
    
      {% with comments.count as total_comments %}
        <h4 class="my-font">
          {{ total_comments }} comment{{ total_comments|pluralize }}
        </h4>
      {% endwith %}
    
      {% for comment in comments %}
        <div class="comment">
          <span style="font-size: 18px;">{{ comment.body}}</span>
          <br>
          <span style="opacity: 0.6;">
            <small>
              <a class="author-only-link" style="font-size: 14px;" href="{% url 'blog:user-posts' comment.author.username %}">{{ comment.author.username }}</a>
              {{ comment.created }}
          </small>
          </span>
        </div>
      {% empty %}
          <p>There are no comments yet.</p>
      {% endfor %}
        <br>
      <form action="." method="POST">
        {% csrf_token %}
        {{ comment_form|crispy }}  
        <p><button class="btn-update my-font">Comment</button class="my-font"></p>
      </form>

      <div id="like-section">
        {% include 'blog/like_section.html' %}
      </div>
      
  </div>


  <div class="col-4">

        <h4 class="my-font" style='font-weight: 700; color: rgb(90, 90, 90);'>Similar Posts -</h4>
        <div class="border-for-similar">
        {% for post in similar_posts %}
          <div class="similar-posts-box">
            <div class="similar-posts-title">
              <strong>
                <a class="my-link-title my-font" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
              </strong>
            </div>
            <div class="tags">
                {% for tag in post.tags.all %}
                  <a class="my-link-tag my-font badge badge-info" href="{% url 'blog:post-list-by-tag' tag.slug %}">
                    {{ tag.name }}
                  </a>
                <!-- {% if not forloop.last %}, {% endif %} -->
                {% endfor %}
            </div>
            <div class="my-font2">{{post.body|truncatewords:12}}</div>
          </div>
        {% empty %}
          There are no similar posts yet.
        {% endfor %}
        </div>
      
       
  </div>
</div>

 {% endblock %}

blog/templates/blog/post_form.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Blog Post</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Post</button>
            </div>
        </form>
    </div>
{% endblock content %}

blog/templates/blog/post_list.html
{% extends "blog/base.html" %}

{% block title %}
  {{user.username}}'s - news feeds
{% endblock %}


{% block content %}
<div id="login-background">
  <div class="row">
      <div class="col-8">      
          <div class="search-create">
              <div class="img-user"><a href="{% url 'profile' %}"><img class="img-circle" src="{{ user.profile.image.url }}"></a></div>
              <div class="search-box"> 
                <form action="{% url 'blog:post-by-search' %}" method="get">
                    <input class="search-box" name="q" type="text" placeholder="Search...">
                </form>
              </div>
              <div class="create-button"> <a href="{% url 'blog:post-create' %}">
                <button class="btn-add1 float-right">
                  <i class="fa fa-plus" style="font-size: 20px; color:green"></i> Add Post
                </button></a>
              </div>
          </div>
      
          {% if tag %}
            <h4 class="my-font ">Posts tagged with <span class="badge badge-info">{{ tag.name }}</span></h4>
          {% endif %}
      
          <div class="infinite-container">
            {% for post in posts %}
            <div class="post-box infinite-item">
                <div class="content-section">
                  <div class="img-section"><a href="{% url 'blog:user-posts' post.author.username %}"><img class="img-circle" src="{{ post.author.profile.image.url }}"></a></div>
                  <div class="title-author">
                    <div class="author-publish">
                      <div > <a class="author-only-link" href="{% url 'blog:user-posts' post.author.username %}">@{{post.author}}</a></div>
                      <div class="publish-only">{{post.publish|date:"b d, Y P"}}</div>
                    </div>
                    <div class="only-title"> <a class="only-title-link" href="{% url 'blog:post-detail' post.id %}">{{post.title}}</a></div>
                    
                    <div class="tags">
                      {% for tag in post.tags.all %}
                        <a class="my-link-tag badge badge-info" href="{% url 'blog:post-list-by-tag' tag.slug %}">
                          {{ tag.name }}
                        </a>
                      <!-- {% if not forloop.last %}, {% endif %} -->
                      {% endfor %}
                    </div>
                    
                  </div>
                </div>
      
                <div class="content-body">
                    {{post.body|safe|linebreaks|truncatechars:420}} 
                      {% if post.body|length >= 420 %} 
                        <a class="only-body-link" href="{% url 'blog:post-detail' post.id %}">
                          <span id="read-more">read more</span> 
                        </a>
                      {% endif %}
                  <div><strong>Book:</strong> {{ post.book_name }}</div>
                  <div><strong>Author:</strong> {{ post.author_name }}</div>
                </div>
      
                <div id="comment-like">
                  <a class="comment-like-link" href="{% url 'blog:post-detail' post.id %}">
                    <i class="fa fa-heart-o" style="font-size:20px;color:rgb(221, 90, 90)"></i>
                    <span style="font-size: 18px; color: black; font-family: 'Barlow', sans-serif;" >{{ post.likes.count }} like{{ post.likes.count|pluralize }}</span> 
                    <i class="fa fa-comment-o" style="font-size:23px;color:rgb(19, 146, 29)"></i>
                    <span style="font-size: 18px; color: black; font-family: 'Barlow', sans-serif;">{{ post.post_comments.count }} comment{{ post.post_comments.count|pluralize }}</span> 
                    <i class="fa fa-caret-right" style="font-size:20px;color:#0c6690;"></i>
                  </a>
                </div>
              </div>
            {% endfor %}
          </div>
      
          {% include "blog/pagination.html" with page=posts %}    
      </div>


      <div class="col-4">
        <h3 style='font-weight: 700; color: rgb(90, 90, 90);' class="my-font">Popular Tags</h3>
          {% for t in commontags %}
            <h5>
              <a class="my-link-tag badge badge-info" href="{% url 'blog:post-list-by-tag' t.slug %}">
                #{{ t }}
              </a>
            </h5>
          {% endfor %}
      </div>
  </div>
</div>
{% endblock %}

blog/templates/blog/user_posts.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="profile-content-section1">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ thisuser.profile.image.url }}">
        </div>
        <div class="profile-username">@{{ thisuser.username }}</div>
    </div>      
        

    <div class="profile-user-posts">  
        <div class="infinite-container" >
            {% for post in posts %}
            <div class="post-box infinite-item">
                <div class="content-section">
                    <div class="img-section"><a href="{% url 'blog:user-posts' post.author.username %}"><img class="img-circle" src="{{ post.author.profile.image.url }}"></a></div>
                    <div class="title-author">
                    <div class="author-publish">
                        <div > <a class="author-only-link" href="{% url 'blog:user-posts' post.author.username %}">@{{post.author}}</a></div>
                        <div class="publish-only">{{post.publish|date:"b d, Y P"}}</div>
                    </div>
                    <div class="only-title"> <a class="only-title-link" href="{% url 'blog:post-detail' post.id %}">{{post.title}}</a></div>
                    
                    <div class="tags">
                        {% for tag in post.tags.all %}
                        <a class="my-link-tag badge badge-info" href="{% url 'blog:post-list-by-tag' tag.slug %}">
                            {{ tag.name }}
                        </a>
                        {% endfor %}
                    </div>
                    
                    </div>
                </div>
        
                <div class="content-body">
                    {{post.body|safe|linebreaks|truncatechars:420}} 
                        {% if post.body|length >= 420 %} 
                        <a class="only-body-link" href="{% url 'blog:post-detail' post.id %}">
                            <span id="read-more">read more</span> 
                        </a>
                        {% endif %}
                    <div><strong>Book:</strong> {{ post.book_name }}</div>
                    <div><strong>Author:</strong> {{ post.author_name }}</div>
                </div>
        
                <div id="comment-like">
                    <a class="comment-like-link" href="{% url 'blog:post-detail' post.id %}">
                    <i class="fa fa-heart-o" style="font-size:20px;color:rgb(221, 90, 90)"></i>
                    <span style="font-size: 18px; color: black; font-family: 'Barlow', sans-serif;" >{{ post.likes.count }} like{{ post.likes.count|pluralize }}</span> 
                    <i class="fa fa-comment-o" style="font-size:23px;color:rgb(19, 146, 29)"></i>
                    <span style="font-size: 18px; color: black; font-family: 'Barlow', sans-serif;">{{ post.post_comments.count }} comment{{ post.post_comments.count|pluralize }}</span> 
                    <i class="fa fa-caret-right" style="font-size:20px;color:#0c6690;"></i>
                    </a>
                </div>
                </div>
            {% endfor %}
            </div>
            {% include "blog/pagination.html" with page=posts %}    
        </div>

{% endblock content %}