blog/urls.py
from django.urls import path
from .views import (
    PostListView, 
    PostDetailView, 
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    UserPostListView,
    like_post,
)

app_name = 'blog'

urlpatterns = [
    path('',PostListView, name='post-list'),
    path('tag/<slug:tag_slug>/',PostListView, name='post-list-by-tag'),
    path('search/',PostListView, name='post-by-search'),
    path('<int:pk>/',PostDetailView,name='post-detail'),
    path('user/<str:username>', UserPostListView, name='user-posts'), 
    path('<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),    
    path('new/', PostCreateView.as_view(),name='post-create'),
    path('like/', like_post, name='like'),
]

coverprey/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from users import views as user_views
from django.contrib.auth import views as auth_views
from users.forms import CustomAuthForm


urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(authentication_form=CustomAuthForm, 
            template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('oauth/',include('social_django.urls', namespace='social')),
    path('admin/', admin.site.urls),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__', include(debug_toolbar.urls))]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    bio = models.TextField(blank=True)
    location = models.CharField(max_length=200, blank=True)
    image = models.ImageField(default='default.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self, *args, **kwargs):
        super(Profile, self).save(*args, **kwargs)

        img = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path)

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.forms.widgets import PasswordInput, TextInput
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'placeholder': 'username'})
        self.fields['email'].widget.attrs.update({'placeholder':'email'})
        self.fields['password1'].widget.attrs.update({'placeholder':'password'})
        self.fields['password2'].widget.attrs.update({'placeholder':'confirm password'})



class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()
    email.widget.attrs.update({'class': 'user-email'})

    class Meta:
        model = User
        fields = ['email',]



class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['bio', 'location', 'image',]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['bio'].widget.attrs.update({'class': 'user-bio'})
        self.fields['location'].widget.attrs.update({'class':'user-location'})
        self.fields['image'].widget.attrs.update({'class':'user-image'})

class CustomAuthForm(AuthenticationForm):
    username = forms.CharField(widget=TextInput(attrs={'placeholder': 'username', 'id':'id_username_login'}))
    password = forms.CharField(widget=PasswordInput(attrs={'placeholder':'password'}))

users/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import messages
from blog.models import Post


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('login')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})
    

@login_required(login_url='/login/')
def profile(request):
    user = get_object_or_404(User, username=request.user.username)
    posts = Post.objects.filter(author=user)

    paginator = Paginator(posts, 4) # 4 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)



    if request.POST:
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST,
                                   request.FILES, 
                                   instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'Your profile has been updated!')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
    context = {
        'u_form' : u_form,
        'p_form' : p_form,
        'posts' : posts,
        'page' : page,
    }

    return render(request, 'users/profile.html', context)

users/templates/users/login.html
{% extends "blog/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    
    <div class="adjustit">
        <div class="login-form">
            <form method="POST">
                {% csrf_token %}
                <fieldset>
                    <legend><span id="login-text" >Log In</span></legend>
                    <hr align="center" width="90%">
                    <p>{{ form.username }}</p>  
                    <p>{{ form.password }}</p>
                    <!-- {{ form|crispy }} -->
                    
                </fieldset>
                <div class="login-form-button-div">
                    <button class="login-form-button" type="submit">Login</button>
                </div>
                <hr align="center" width="90%">
                <div id="facebook-login-div" >
                    <a id="facebook-login" href="{% url 'social:begin' 'facebook' %}">
                        <i class="fa fa-facebook-f" style="font-size:25px"></i>
                        Continue with facebook
                    </a>
                </div>
            </form>
            <div class="login-footer">
                Need An Account? <a class="ml-2 signup-footer" href="{% url 'register' %}">Sign Up</a>
            </div>
        </div>
    </div>
    
{% endblock content %}

users/templates/users/profile.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="profile-content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ user.profile.image.url }}">
        </div>
        <div class="profile-username">@{{ user.username }}</div>
            <!-- FORM HERE -->
        <div class="profile-form-content">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="profile-form">
                    {{ u_form.as_p }}
                    {{ p_form.as_p }}
                </fieldset>
                <div>
                    <button class="btn-update" type="submit">Update</button>
                </div>
            </form>
        </div>
    </div>      
        

    <div class="profile-user-posts">  
        <div class="infinite-container" >
            {% for post in posts %}
            <div class="post-box infinite-item">
                <div class="content-section">
                    <div class="img-section"><a href="{% url 'blog:user-posts' post.author.username %}"><img class="img-circle" src="{{ post.author.profile.image.url }}"></a></div>
                    <div class="title-author">
                    <div class="author-publish">
                        <div > <a class="author-only-link" href="{% url 'blog:user-posts' post.author.username %}">@{{post.author}}</a></div>
                        <div class="publish-only">{{post.publish|date:"b d, Y P"}}</div>
                    </div>
                    <div class="only-title"> <a class="only-title-link" href="{% url 'blog:post-detail' post.id %}">{{post.title}}</a></div>
                    
                    <div class="tags">
                        {% for tag in post.tags.all %}
                        <a class="my-link-tag badge badge-info" href="{% url 'blog:post-list-by-tag' tag.slug %}">
                            {{ tag.name }}
                        </a>
                        {% endfor %}
                    </div>
                    
                    </div>
                </div>
        
                <div class="content-body">
                    {{post.body|safe|linebreaks|truncatechars:420}} 
                        {% if post.body|length >= 420 %} 
                        <a class="only-body-link" href="{% url 'blog:post-detail' post.id %}">
                            <span id="read-more">read more</span> 
                        </a>
                        {% endif %}
                    <div><strong>Book:</strong> {{ post.book_name }}</div>
                    <div><strong>Author:</strong> {{ post.author_name }}</div>
                </div>
        
                <div id="comment-like">
                    <a class="comment-like-link" href="{% url 'blog:post-detail' post.id %}">
                    <i class="fa fa-heart-o" style="font-size:20px;color:rgb(221, 90, 90)"></i>
                    <span style="font-size: 18px; color: black; font-family: 'Barlow', sans-serif;" >{{ post.likes.count }} like{{ post.likes.count|pluralize }}</span> 
                    <i class="fa fa-comment-o" style="font-size:23px;color:rgb(19, 146, 29)"></i>
                    <span style="font-size: 18px; color: black; font-family: 'Barlow', sans-serif;">{{ post.post_comments.count }} comment{{ post.post_comments.count|pluralize }}</span> 
                    <i class="fa fa-caret-right" style="font-size:20px;color:#0c6690;"></i>
                    </a>
                </div>
                </div>
            {% endfor %}
            </div>
            {% include "blog/pagination.html" with page=posts %}    
        </div>

{% endblock content %}

users/templates/users/register.html
{% extends "blog/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

        <div id="adjustit">
            <div class="signup-form">
                <form method="POST">
                    {% csrf_token %}
                    <fieldset>
                        <legend><span id="login-text" >Sign Up</span></legend>
                        <hr align="center" width="90%">
                        <br>
                        {{ form|crispy }}
                        
                    </fieldset>
                    <div class="login-form-button-div">
                        <button class="login-form-button" type="submit">Sign Up</button>
                    </div>
                    <hr align="center" width="90%">
                </form>
                <div class="login-footer">
                    Already have an Account? <a class="ml-2 signup-footer" href="{% url 'login' %}">Log In</a>
                </div>
            </div>
        </div>




{% endblock content %}